# Publish all joint states
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# Control all joints
arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - jright_shoulder
    - jright_upper_arm
    - jright_forearm
  gains:
      jright_shoulder:
        p: 100
        i: 0.01
        d: 10
        i_clamp: 1
      jright_upper_arm:
        p: 100
        i: 0.01
        d: 10
        i_clamp: 1   
      jright_forearm:
        p: 100
        i: 0.01
        d: 10
        i_clamp: 1 

#  gains:
#    jright_shoulder: {p: 100.0, i: 0.01, d: 10.0, i_clamp: 1}
#    jright_upper_arm: {p: 100.0, i: 0.01, d: 10.0, i_clamp: 1}
#    jright_forearm: {p: 100.0, i: 0.01, d: 10.0, i_clamp: 1}
#  constraints: 
#      goaltime: 0.6
#      stopped_velocity_tolerance: 0.05
#      jright_shoulder: {trajectory: 0.1, goal: 0.1}
#      jright_upper_arm: {trajectory: 0.1, goal: 0.1}
#      jright_forearm: {trajectory: 0.1, goal: 0.1}

#  stop_trajectory_duration: 0.5
#  state_publish_rate: 25
#  action_monitor_rate: 10
      
gripper_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - jright_wrist
    - jright_grip_rhand
  gains:
      jright_wrist:
        p: 100
        i: 0.01
        d: 10
        i_clamp: 1
      jright_grip_rhand:
        p: 100
        i: 0.01
        d: 10
        i_clamp: 1

#  gains:  
#    jright_wrist: {p: 100.0, i: 0.01, d: 10.0, i_clamp: 1}
#    jright_grip_rhand: {p: 100.0, i: 0.01, d: 10.0, i_clamp: 1}

#  constraints: 
#      goaltime: 0.6
#      stopped_velocity_tolerance: 0.05
#      jright_grip_rhand: {trajectory: 0.1, goal: 0.1}

#  stop_trajectory_duration: 0.5
#  state_publish_rate: 25
#  action_monitor_rate: 10
